class Homepage_Locators:
    # item images xpaths
    nokia_lumina_1520_image_xpath = '//*[@id="tbodyid"]/div[1]/div/a/img'
    nexus_6_image_xpath = '//*[@id="tbodyid"]/div[2]/div/a/img'
    samsung_galaxy_s7_image_xpath = '//*[@id="tbodyid"]/div[3]/div/a/img'
    iphone_6_32gb_image_xpath = '//*[@id="tbodyid"]/div[4]/div/a/img'
    sony_xperia_z5_image_xpath = '//*[@id="tbodyid"]/div[5]/div/a/img'
    HTC_one_m9_image_xpath = '//*[@id="tbodyid"]/div[6]/div/a/img'
    sony_vaio_i5_image_xpath = '//*[@id="tbodyid"]/div[7]/div/a/img'
    sony_vaio_i7_image_xpath = '//*[@id="tbodyid"]/div[8]/div/a/img'
    apple_monitor_24_image_xpath = '//*[@id="tbodyid"]/div[9]/div/a/img'
    macbook_air_image_xpath = '//*[@id="tbodyid"]/div[1]/div/a/img'
    dell_i7_8gb_image_xpath = '//*[@id="tbodyid"]/div[2]/div/a/img'
    laptop_2017_dell_15_inch_image_xpath = '//9*[@id="tbodyid"]/div[3]/div/a/img'
    asus_full_hd_image_xpath = '//*[@id="tbodyid"]/div[4]/div/a/img'
    macbook_pro_image_xpath = '//*[@id="tbodyid"]/div[5]/div/a/img'

    # item links xpaths
    nokia_lumina_1520_link_xpath = '//*[@id="tbodyid"]/div[4]/div/div/h4/a'
    nexus_6_link_xpath = '//*[@id="tbodyid"]/div[2]/div/div/h4/a'
    samsung_galaxy_s7_link_xpath = '//*[@id="tbodyid"]/div[3]/div/div/h4/a'
    iphone_6_32gb_link_xpath = '//*[@id="tbodyid"]/div[4]/div/div/h4/a'
    sony_xperia_z5_link_xpath = '//*[@id="tbodyid"]/div[5]/div/div/h4/a'
    HTC_one_m9_link_xpath = '//*[@id="tbodyid"]/div[6]/div/div/h4/a'
    sony_vaio_i5_link_xpath = '//*[@id="tbodyid"]/div[7]/div/div/h4/a'
    sony_vaio_i7_link_xpath = '//*[@id="tbodyid"]/div[8]/div/div/h4/a'
    apple_monitor_24_link_xpath = '//*[@id="tbodyid"]/div[9]/div/div/h4/a'
    macbook_air_link_xpath = '//*[@id="tbodyid"]/div[1]/div/div/h4/a'
    dell_i7_8gb_link_xpath = '//*[@id="tbodyid"]/div[2]/div/div/h4/a'
    laptop_2017_dell_15_inch_link_xpath = '//*[@id="tbodyid"]/div[3]/div/div/h4/a'
    asus_full_hd_link_xpath = '//*[@id="tbodyid"]/div[4]/div/div/h4/a'
    macbook_pro_link_xpath = '//*[@id="tbodyid"]/div[5]/div/div/h4/a'

    # item price xpaths
    nokia_lumina_1520_price_xpath = '//*[@id="tbodyid"]/div[5]/div/div/h4/a'
    nexus_6_price_xpath = '//*[@id="tbodyid"]/div[2]/div/div/h5'
    samsung_galaxy_s7_price_xpath = '//*[@id="tbodyid"]/div[3]/div/div/h5'
    iphone_6_32gb_price_xpath = '//*[@id="tbodyid"]/div[4]/div/div/h5'
    sony_xperia_z5_price_xpath = '//*[@id="tbodyid"]/div[5]/div/div/h4/a'
    HTC_one_m9_price_xpath = '//*[@id="tbodyid"]/div[6]/div/div/h5'
    sony_vaio_i5_price_xpath = '//*[@id="tbodyid"]/div[7]/div/div/h5'
    sony_vaio_i7_price_xpath = '//*[@id="tbodyid"]/div[8]/div/div/h5'
    apple_monitor_24_price_xpath = '//*[@id="tbodyid"]/div[9]/div/div/h5'
    macbook_air_price_xpath = '//*[@id="tbodyid"]/div[1]/div/div/h5'
    dell_i7_8gb_price_xpath = '//*[@id="tbodyid"]/div[2]/div/div/h5'
    laptop_2017_dell_15_inch_price_xpath = '//*[@id="tbodyid"]/div[3]/div/div/h5'
    asus_full_hd_price_xpath = '//*[@id="tbodyid"]/div[4]/div/div/h5'
    macbook_pro_price_xpath = '//*[@id="tbodyid"]/div[5]/div/div/h5'

    # item description xpath
    nokia_lumina_1520_description_xpath = '/html/body/div[5]/div/div[2]/div/div[1]/div/div/p'
    nexus_6_description_xpath = '/html/body/div[5]/div/div[2]/div/div[2]/div/div/p'
    samsung_galaxy_s7_description_xpath = '/html/body/div[5]/div/div[2]/div/div[3]/div/div/p'
    iphone_6_32gb_description_xpath = '/html/body/div[5]/div/div[2]/div/div[4]/div/div/p'
    sony_xperia_z5_description_xpath = '/html/body/div[5]/div/div[2]/div/div[5]/div/div/p'
    HTC_one_m9_description_xpath = '/html/body/div[5]/div/div[2]/div/div[6]/div/div/p'
    sony_vaio_i5_description_xpath = '/html/body/div[5]/div/div[2]/div/div[7]/div/div'
    sony_vaio_i7_description_xpath = '/html/body/div[5]/div/div[2]/div/div[8]/div/div/p'
    apple_monitor_24_description_xpath = '/html/body/div[5]/div/div[2]/div/div[9]/div/div/p'
    macbook_air_description_xpath = '/html/body/div[5]/div/div[2]/div/div[1]/div/div/p'
    dell_i7_8gb_description_xpath = '/html/body/div[5]/div/div[2]/div/div[2]/div/div/p'
    laptop_2017_dell_15_inch_description_xpath = '/html/body/div[5]/div/div[2]/div/div[3]/div/div/p'
    asus_full_hd_description_xpath = '/html/body/div[5]/div/div[2]/div/div[4]/div/div/p'
    macbook_pro_description_xpath = '/html/body/div[5]/div/div[2]/div/div[4]/div/div/p'
