class PlaceOrderLocators:
    place_order_txt = '/html/body/div[3]/div/div/div[1]/h5'
    total_txt = 'totalm'
    name_field_id = 'name'
    country_field_id = 'country'
    city_field_id = 'city'
    credit_card_field_id = 'card'
    month_field_id = 'month'
    year_field_id = 'year'
    purchase_btn_xpath = '/html/body/div[3]/div/div/div[3]/button[2]'
    close_btn_xpath = '/html/body/div[3]/div/div/div[3]/button[1]'
    x_button_xptah = '/html/body/div[3]/div/div/div[1]/button/span'
